import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
export const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');export const CONTENT=path.join(ROOT,'content');export const DIST=path.join(ROOT,'dist');
export const ensureDir=d=>fs.mkdirSync(d,{recursive:true});
export const readJson=(f,d={})=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}};
export const readText=f=>fs.readFileSync(f,'utf8');
export const writeText=(f,s)=>{ensureDir(path.dirname(f));fs.writeFileSync(f,s)};
export const listFiles=d=>{if(!fs.existsSync(d))return[];let o=[];for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?o.push(...listFiles(p)):o.push(p)}return o};
export const slugify=s=>String(s).normalize('NFKD').replace(/[^\w\s-]/g,'').trim().toLowerCase().replace(/\s+/g,'-').replace(/-+/g,'-')||'item';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const plain=s=>s.replace(/[#>*_\[\]]/g,' ').replace(/\s+/g,' ').trim();
export const gitTime=p=>{try{return execFileSync('git',['log','-1','--format=%cI','--',p],{cwd:ROOT,encoding:'utf8'}).trim()}catch{return new Date().toISOString()}};
export const copyTree=(s,d)=>{ensureDir(d);for(const e of fs.readdirSync(s,{withFileTypes:true})){const a=path.join(s,e.name),b=path.join(d,e.name);e.isDirectory()?copyTree(a,b):fs.copyFileSync(a,b)}};
export const encryptBuffer=(buf,pwd)=>{const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),iterations=210000,key=crypto.pbkdf2Sync(Buffer.from(pwd,'utf8'),salt,iterations,32,'sha256'),c=crypto.createCipheriv('aes-256-gcm',key,iv),enc=Buffer.concat([c.update(buf),c.final()]),tag=c.getAuthTag(),h=Buffer.from(JSON.stringify({version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA-256',iterations,salt:salt.toString('base64'),iv:iv.toString('base64')})),n=Buffer.alloc(4);n.writeUInt32LE(h.length);return Buffer.concat([n,h,enc,tag])};
export const dataJsonFile=b=>JSON.stringify({data:b.toString('base64')});